// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PhEnvelopeSimple: typeof import('./src/components/icons/PhEnvelopeSimple.vue')['default']
    PhMapPin: typeof import('./src/components/icons/PhMapPin.vue')['default']
    PhPhone: typeof import('./src/components/icons/PhPhone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
